#!/usr/bin/env node
// Build the mapshaper docs site.
//
//   - Reads markdown sources from docs/
//   - Reads navigation from docs/_nav.json
//   - Wraps rendered content in docs/_layout.html
//   - Copies docs/_assets/ verbatim
//   - Writes the resulting static site to www/docs/
//
// Run with: npm run docs

import { Marked } from 'marked';
import hljs from 'highlight.js';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(HERE, 'docs');
const WWW_DIR = path.join(HERE, 'www');
const OUT_DIR = path.join(WWW_DIR, 'docs');
const LAYOUT_PATH = path.join(SRC_DIR, '_layout.html');
const NAV_PATH = path.join(SRC_DIR, '_nav.json');
const ASSETS_DIR = path.join(SRC_DIR, '_assets');
const LLMS_INTRO_PATH = path.join(SRC_DIR, '_llms.md');

// Public origin used to build absolute URLs in llms.txt and the .html.md
// mirror pages. Both files are designed to be machine-consumable, so links
// must work even when the file has been fetched and re-hosted elsewhere.
const SITE_URL = 'https://mapshaper.org';

// --- helpers ----------------------------------------------------------

function readFile(p) { return fs.readFileSync(p, 'utf8'); }

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  ensureDir(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else if (entry.isFile()) fs.copyFileSync(s, d);
  }
}

// Slugify heading text into an anchor id. Designed to preserve leading
// hyphens so commands like "-i (input)" become id "-i-input", matching
// the anchor scheme used by the existing wiki Command Reference.
function slugify(text) {
  return text.toLowerCase()
    .replace(/[()`'".,:;!?*]/g, '')
    .replace(/[^a-z0-9_\-\s]/g, ' ')
    .trim()
    .replace(/\s+/g, '-');
}

// Recursively extract plain text from marked inline tokens.
function tokensToText(tokens = []) {
  return tokens.map(t => {
    if (typeof t.text === 'string' && !t.tokens) return t.text;
    if (t.tokens) return tokensToText(t.tokens);
    return '';
  }).join('');
}

// Parse simple --- yaml-ish frontmatter at the top of a markdown file.
// Recognises `key: value` pairs only (no nested structures).
function parseFrontmatter(src) {
  const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { meta: {}, body: src };
  const meta = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim();
  }
  return { meta, body: src.slice(m[0].length) };
}

// --- nav --------------------------------------------------------------

const nav = JSON.parse(readFile(NAV_PATH));

// Build a flat list of pages, with their output URL and source path. Top
// links and sidebar entries can be either a "page" (defined by `file:` and
// turned into a generated HTML page) or a "link" (defined by `url:` and
// pointing at a URL elsewhere -- typically a page generated by a different
// nav entry).
function expandPages() {
  const pages = [];
  for (const link of nav.topLinks || []) {
    if (!link.file) continue;
    pages.push({
      kind: 'top',
      label: link.label,
      file: link.file,
      sourcePath: path.join(SRC_DIR, link.source || link.file),
      outRel: link.file.replace(/\.md$/, '.html'),
      url: '/docs/' + link.file.replace(/\.md$/, '.html').replace(/\/index\.html$/, '/'),
      sectionLabel: null,
      transform: link.transform || null,
    });
  }
  // Special-case the home page URL as /docs/
  for (const p of pages) {
    if (p.outRel === 'index.html') p.url = '/docs/';
  }
  for (const section of nav.sections || []) {
    for (const page of section.pages) {
      if (!page.file) continue;
      const rel = path.join(section.path, page.file);
      pages.push({
        kind: 'section',
        label: page.label,
        file: page.file,
        sectionLabel: section.label,
        sectionPath: section.path,
        sourcePath: page.source
          ? path.resolve(SRC_DIR, section.path, page.source)
          : path.join(SRC_DIR, rel),
        outRel: rel.replace(/\.md$/, '.html'),
        url: '/docs/' + rel.replace(/\.md$/, '.html').replace(/\/index\.html$/, '/'),
        transform: page.transform || null,
      });
    }
  }
  return pages;
}

const allPages = expandPages();

function renderNavHtml(currentUrl) {
  const out = ['<nav class="docs-nav">'];
  out.push('<ul class="top-links">');
  for (const link of nav.topLinks || []) {
    const url = link.file
      ? (allPages.find(p => p.kind === 'top' && p.file === link.file) || {}).url
      : link.url;
    if (!url) continue;
    const active = url === currentUrl ? ' class="is-active"' : '';
    out.push(`<li><a href="${url}"${active}>${escapeHtml(link.label)}</a></li>`);
  }
  out.push('</ul>');
  for (const section of nav.sections || []) {
    out.push(`<h2>${escapeHtml(section.label)}</h2><ul>`);
    for (const page of section.pages) {
      let url;
      if (page.file) {
        const p = allPages.find(x => x.kind === 'section'
          && x.sectionPath === section.path && x.file === page.file);
        url = p ? p.url : null;
      } else {
        url = page.url;
      }
      if (!url) continue;
      const active = url === currentUrl ? ' class="is-active"' : '';
      out.push(`<li><a href="${url}"${active}>${escapeHtml(page.label)}</a></li>`);
    }
    out.push('</ul>');
  }
  out.push('</nav>');
  return out.join('');
}

function renderBreadcrumbs(page) {
  if (page.kind !== 'section') return '';
  // The section name is rendered as plain text rather than a link, because
  // there is no longer a landing page at /docs/<section>/ -- each section's
  // first nav entry is a regular content page (e.g. command-line.md, basics.md,
  // overview.md).
  return `<div class="docs-breadcrumbs"><a href="/docs/">Docs</a> &rsaquo; ` +
    `${escapeHtml(page.sectionLabel)} &rsaquo; ` +
    `${escapeHtml(page.label)}</div>`;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
}

// --- example pre-processor -------------------------------------------

// HTML-comment placeholders that the docs build resolves at render time.
//
// Per-example placeholders (resolved from the page's own frontmatter, with
// asset files looked up in a sibling `data/` directory of the page source):
//
//   <!-- mapshaper:image -->    replaced with an <img> built from `image:`
//   <!-- mapshaper:code -->     replaced with a fenced bash block from `recipe:`
//   <!-- mapshaper:assets -->   replaced with a list of download links built
//                               from `snapshot:` and `download:`, including a
//                               one-click "Open in web app" link when a
//                               snapshot is available.
//
// Cross-page placeholders (resolved by walking the nav, no frontmatter
// dependency):
//
//   <!-- mapshaper:gallery -->            tile grid of every page in the
//                                         Examples section that declares
//                                         `image:` in its frontmatter, in
//                                         nav order.
//   <!-- mapshaper:featured count=N -->   compact strip of the first N
//                                         examples (defaults to 2). Same
//                                         tile markup but wrapped in
//                                         `.featured-maps` and with the
//                                         description suppressed, for use
//                                         on the home page.
//
// References to missing files throw, since a typo here would otherwise
// silently produce a broken page.
function preprocessExample(body, meta, page) {
  body = body.replace(/<!--\s*mapshaper:gallery\s*-->/g,
    () => renderExampleTiles({ variant: 'gallery' }));
  body = body.replace(/<!--\s*mapshaper:featured(?:\s+count=(\d+))?\s*-->/g,
    (_, n) => renderExampleTiles({
      variant: 'featured',
      limit: n ? parseInt(n, 10) : 2
    }));
  if (!meta.recipe && !meta.image && !meta.snapshot && !meta.download) {
    return body;
  }
  const pageDir = path.dirname(page.sourcePath);
  const dataDir = path.join(pageDir, 'data');
  const dataUrlBase = path.posix.join('/docs',
    path.dirname(page.outRel).split(path.sep).join('/'), 'data');

  function requireFile(kind, name) {
    const p = path.join(dataDir, name);
    if (!fs.existsSync(p)) {
      throw new Error(
        `${page.sourcePath}: ${kind} file "${name}" not found at ${p}`);
    }
    return p;
  }

  body = body.replace(/<!--\s*mapshaper:image\s*-->/g, () => {
    if (!meta.image) return '';
    requireFile('image', meta.image);
    const alt = (meta.title || page.label || meta.image).replace(/[\[\]]/g, '');
    const url = path.posix.join(dataUrlBase, meta.image);
    return `![${alt}](${url})`;
  });

  body = body.replace(/<!--\s*mapshaper:code\s*-->/g, () => {
    if (!meta.recipe) return '';
    const recipePath = requireFile('recipe', meta.recipe);
    const code = fs.readFileSync(recipePath, 'utf8').replace(/\s+$/, '');
    return '```bash\n' + code + '\n```';
  });

  body = body.replace(/<!--\s*mapshaper:assets\s*-->/g, () => {
    const lines = [];
    if (meta.snapshot) {
      requireFile('snapshot', meta.snapshot);
      const snapUrl = path.posix.join(dataUrlBase, meta.snapshot);
      const absSnapUrl = SITE_URL + snapUrl;
      // `&q` skips the import dialog so the map appears immediately.
      // CLI .msx exports already pin every targeted layer visible, so no
      // `&display-all` flag is needed for finished gallery snapshots.
      // The link is rewritten at page load by `_assets/docs.js` to point at
      // the current origin, so it also works when the docs are previewed
      // locally via `mapshaper-gui` (which serves `www/` on `localhost:NNNN`).
      const openUrl = `${SITE_URL}/?files=${encodeURIComponent(absSnapUrl)}&q`;
      lines.push(`- <a href="${openUrl}" data-open-snapshot="${snapUrl}">Open in the web app</a> &mdash; loads a snapshot file containing the finished map`);
      lines.push(`- [Download snapshot (\`${meta.snapshot}\`)](${snapUrl})`);
    }
    if (meta.download) {
      requireFile('download', meta.download);
      const dlUrl = path.posix.join(dataUrlBase, meta.download);
      lines.push(`- [Download source data (\`${meta.download}\`)](${dlUrl})`);
    }
    return lines.join('\n');
  });

  return body;
}

// Walk the Examples section in nav order and collect a tile descriptor for
// every page that declares an `image:` in its frontmatter. Cached so we
// don't re-read every example's source for each render pass.
let exampleTilesCache = null;
function getExampleTiles() {
  if (exampleTilesCache) return exampleTilesCache;
  const examplesSection = (nav.sections || []).find(s => s.path === 'examples');
  if (!examplesSection) {
    exampleTilesCache = [];
    return exampleTilesCache;
  }
  const tiles = [];
  for (const navEntry of examplesSection.pages) {
    if (!navEntry.file) continue;
    const page = allPages.find(p =>
      p.kind === 'section' &&
      p.sectionPath === examplesSection.path &&
      p.file === navEntry.file);
    if (!page) continue;
    const src = readFile(page.sourcePath);
    const { meta, body } = parseFrontmatter(src);
    if (!meta.image) continue;
    const dataUrlBase = path.posix.join('/docs',
      path.dirname(page.outRel).split(path.sep).join('/'), 'data');
    // Prefer the page's H1 over the frontmatter `title:`, since H1s tend to
    // be polished display prose ("Globe locator map") while `title:` is
    // often terse for nav/browser-tab use ("Globe").
    const h1Match = body.match(/^#\s+(.+?)\s*$/m);
    const title = (h1Match && h1Match[1].trim())
      || meta.title || navEntry.label || page.label;
    tiles.push({
      url: page.url,
      imageUrl: path.posix.join(dataUrlBase, meta.image),
      title: title,
      description: meta.description || ''
    });
  }
  exampleTilesCache = tiles;
  return exampleTilesCache;
}

// Render a strip/grid of example tiles. Two variants:
//
//   variant: 'gallery'   full tile grid (used by docs/gallery/index.md);
//                        shows image, title and description.
//   variant: 'featured'  compact home-page strip; shows image and title only.
//                        `limit` (default 2) bounds the number of tiles.
function renderExampleTiles({ variant = 'gallery', limit = null } = {}) {
  let tiles = getExampleTiles();
  if (limit != null && limit >= 0) tiles = tiles.slice(0, limit);
  if (!tiles.length) return '';
  const showDesc = variant === 'gallery';
  const wrapperClass = variant === 'featured' ? 'featured-maps' : 'gallery-grid';
  const html = tiles.map(tile => {
    const alt = tile.title.replace(/[\[\]]/g, '');
    const descHtml = showDesc && tile.description
      ? `\n      <div class="gallery-tile-desc">${escapeHtml(tile.description)}</div>`
      : '';
    return (
      `  <a class="gallery-tile" href="${tile.url}">\n` +
      `    <div class="gallery-tile-image">\n` +
      `      <img src="${tile.imageUrl}" alt="${escapeHtml(alt)}">\n` +
      `    </div>\n` +
      `    <div class="gallery-tile-caption">\n` +
      `      <div class="gallery-tile-title">${escapeHtml(tile.title)}</div>` +
      descHtml + `\n` +
      `    </div>\n` +
      `  </a>`);
  }).join('\n');
  return `<div class="${wrapperClass}">\n${html}\n</div>`;
}

// --- markdown rendering ----------------------------------------------

function renderPage(page) {
  const src = readFile(page.sourcePath);
  const { meta, body: rawBody } = parseFrontmatter(src);
  const body = preprocessExample(rawBody, meta, page);

  const headings = []; // collected for the on-page TOC
  const seenIds = new Set();
  function uniqueId(base) {
    let id = base || 'section';
    let n = 2;
    while (seenIds.has(id)) id = `${base}-${n++}`;
    seenIds.add(id);
    return id;
  }

  const md = new Marked({
    gfm: true,
    breaks: false,
    renderer: {
      heading({ tokens, depth }) {
        const text = this.parser.parseInline(tokens);
        const plain = tokensToText(tokens);
        const id = uniqueId(slugify(plain));
        if (depth === 2 || depth === 3) {
          headings.push({ depth, id, text: plain });
        }
        return `<h${depth} id="${id}">${text}</h${depth}>\n`;
      },
      code({ text, lang }) {
        return renderCodeBlock(text, lang);
      }
    }
  });

  let contentHtml = md.parse(body);
  if (page.transform === 'command-reference') {
    contentHtml = applyCommandReferenceTransform(contentHtml);
  }
  const tocHtml = renderToc(headings);

  // Determine title: frontmatter > first H1 in source > page label
  let title = meta.title;
  if (!title) {
    const m = body.match(/^#\s+(.+)$/m);
    if (m) title = m[1].trim();
  }
  if (!title) title = page.label;

  const description = meta.description || '';
  const bodyClasses = [];
  if (page.outRel === 'index.html') bodyClasses.push('is-home');
  // Apply the `is-example-map` class to individual map pages in the Examples
  // section -- everything except the "Basics" recipes page, which is a
  // collection of short snippets that don't benefit from copy buttons.
  if (page.kind === 'section' && page.sectionPath === 'examples'
      && page.file !== 'basics.md') {
    bodyClasses.push('is-example-map');
  }
  const bodyClass = bodyClasses.join(' ');

  // Build edit-on-github path. For pages whose content lives outside docs/
  // (e.g. the command reference is sourced from REFERENCE.md), point at
  // that real file so PRs go to the right place.
  let editPath;
  if (page.sourcePath.startsWith(SRC_DIR + path.sep)) {
    editPath = 'docs/' + path.relative(SRC_DIR, page.sourcePath).split(path.sep).join('/');
  } else {
    editPath = path.relative(HERE, page.sourcePath).split(path.sep).join('/');
  }

  const layout = readFile(LAYOUT_PATH);
  const html = layout
    .replace(/\{\{TITLE\}\}/g, escapeHtml(title))
    .replace(/\{\{DESCRIPTION\}\}/g, escapeHtml(description))
    .replace(/\{\{BODY_CLASS\}\}/g, bodyClass)
    .replace(/\{\{NAV_HTML\}\}/g, renderNavHtml(page.url))
    .replace(/\{\{TOC_HTML\}\}/g, tocHtml)
    .replace(/\{\{BREADCRUMBS_HTML\}\}/g, renderBreadcrumbs(page))
    .replace(/\{\{CONTENT\}\}/g, contentHtml)
    .replace(/\{\{EDIT_PATH\}\}/g, editPath);

  return html;
}

// --- code blocks -----------------------------------------------------

// Render a fenced code block. If a language was specified and highlight.js
// recognises it, server-side highlighting is applied; otherwise the content
// is HTML-escaped and emitted verbatim.
function renderCodeBlock(text, lang) {
  const language = (lang || '').toLowerCase();
  if (language && hljs.getLanguage(language)) {
    const highlighted = hljs.highlight(text, { language, ignoreIllegals: true }).value;
    return `<pre><code class="hljs language-${escapeHtml(language)}">${highlighted}\n</code></pre>\n`;
  }
  const cls = language ? ` class="language-${escapeHtml(language)}"` : '';
  return `<pre><code${cls}>${escapeHtml(text)}\n</code></pre>\n`;
}

// --- per-page transforms ---------------------------------------------

// Command reference: wrap every command (h3 with id starting with `-`) and
// the content that follows it (up to the next h2/h3) in a <section> element
// tagged with the command name and a list of its option names. This lets
// cmd-search.js filter the page client-side.
//
// Also injects a sticky search box at the top of the article and pulls in
// the search script.
function applyCommandReferenceTransform(html) {
  const cmdRe = /<h3 id="(-[^"]+)">([\s\S]*?)<\/h3>([\s\S]*?)(?=<h[23][\s>]|$)/g;
  let transformed = html.replace(cmdRe, (full, id, headingInner, body) => {
    const name = stripTags(headingInner).trim();
    const options = extractOptionNames(body);
    const attrs = [
      `class="cmd-section"`,
      `data-id="${escapeAttr(id)}"`,
      `data-name="${escapeAttr(name.toLowerCase())}"`,
      `data-options="${escapeAttr(options.join(' '))}"`,
    ].join(' ');
    return `<section ${attrs}><h3 id="${id}">${headingInner}</h3>${body}</section>\n`;
  });

  // Tag h2s that immediately introduce one or more commands as "categories",
  // so the filter script can hide them when none of their commands match.
  const h2Re = /<h2 id="([^"]+)">([\s\S]*?)<\/h2>([\s\S]*?)(?=<h2[\s>]|$)/g;
  transformed = transformed.replace(h2Re, (full, id, headingInner, body) => {
    if (!/<section class="cmd-section"/.test(body)) return full;
    return `<h2 id="${id}" class="cmd-category">${headingInner}</h2>${body}`;
  });

  const searchBox =
    '<div class="cmd-search-wrap">' +
    '<input type="search" class="cmd-search-input" ' +
    'placeholder="Jump to a command" ' +
    'autocomplete="off" spellcheck="false" ' +
    'role="combobox" aria-autocomplete="list" aria-expanded="false" ' +
    'aria-controls="cmd-search-results" aria-label="Jump to a command">' +
    '<div class="cmd-search-results" id="cmd-search-results" role="listbox" hidden>' +
    '<div class="cmd-search-status" aria-live="polite"></div>' +
    '<ul class="cmd-search-list"></ul>' +
    '</div>' +
    '</div>';

  // Inject the search box right after the H1 (which is the first <h1> tag).
  const withSearch = transformed.replace(
    /(<h1[^>]*>[\s\S]*?<\/h1>\s*(?:<p[^>]*>[\s\S]*?<\/p>\s*)?)/,
    `$1${searchBox}`
  );

  return withSearch +
    '\n<script src="/docs/_assets/cmd-search.js" defer></script>\n';
}

function stripTags(html) {
  return html.replace(/<[^>]+>/g, '');
}

function escapeAttr(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
}

// Extract option-looking tokens from a command's rendered HTML body. Catches
// the common forms used in REFERENCE.md:
//   `option=` description
//   `option` (a flag)
//   `<value>` or `option=` description
// Limited to lowercase-leading identifiers so prose mentions of CamelCase
// or arbitrary code aren't picked up.
function extractOptionNames(bodyHtml) {
  const names = new Set();
  const re = /<code>([a-z][\w-]*)=?<\/code>/g;
  let m;
  while ((m = re.exec(bodyHtml))) {
    const tok = m[1].toLowerCase();
    if (tok.length > 1 || tok === 'i' || tok === 'o') names.add(tok);
  }
  return Array.from(names);
}

function renderToc(headings) {
  if (!headings.length) return '';
  const out = ['<div class="docs-toc-title">On this page</div><ul>'];
  for (const h of headings) {
    out.push(`<li class="lvl-${h.depth}"><a href="#${h.id}">${escapeHtml(h.text)}</a></li>`);
  }
  out.push('</ul>');
  return out.join('');
}

// --- llms.txt + markdown mirrors -------------------------------------

// Rewrite intra-docs links so they point at the markdown mirror instead of
// the human-facing HTML page. Two patterns are handled:
//   /docs/path/foo.html(#anchor)? -> /docs/path/foo.html.md(#anchor)?
//   /docs/path/                   -> /docs/path/index.html.md
// External URLs and non-/docs paths are left alone.
function rewriteLinksToMd(markdown) {
  let out = markdown;
  // /docs/foo/bar.html(#anchor)? -> /docs/foo/bar.html.md(#anchor)?
  out = out.replace(
    /(\]\()(\/docs\/[^)\s#]+?)\.html(#[^)]*)?(\))/g,
    (_, open, base, hash, close) => `${open}${base}.html.md${hash || ''}${close}`
  );
  // /docs/(foo/)?(#anchor)? -> /docs/(foo/)?index.html.md(#anchor)?
  out = out.replace(
    /(\]\()(\/docs\/(?:[^)\s#]*\/)?)(#[^)]*)?(\))/g,
    (_, open, dir, hash, close) => `${open}${dir}index.html.md${hash || ''}${close}`
  );
  // Absolute mapshaper.org docs URLs (used in REFERENCE.md so it remains
  // viewable on GitHub) get the same treatment so the markdown mirrors stay
  // self-contained.
  out = out.replace(
    /(\]\()(https:\/\/mapshaper\.org\/docs\/[^)\s#]+?)\.html(#[^)]*)?(\))/g,
    (_, open, base, hash, close) => `${open}${base}.html.md${hash || ''}${close}`
  );
  out = out.replace(
    /(\]\()(https:\/\/mapshaper\.org\/docs\/(?:[^)\s#]*\/)?)(#[^)]*)?(\))/g,
    (_, open, dir, hash, close) => `${open}${dir}index.html.md${hash || ''}${close}`
  );
  return out;
}

// Resolve a one-line description for a page, preferring frontmatter, then
// any per-page override defined in _nav.json.
function pageDescription(page, navEntry) {
  const { meta } = parseFrontmatter(readFile(page.sourcePath));
  if (meta.description) return meta.description;
  if (navEntry && navEntry.description) return navEntry.description;
  return '';
}

// URL of a page's markdown mirror (always an absolute https URL).
function mdMirrorUrl(page) {
  return `${SITE_URL}/docs/${page.outRel}.md`;
}

// Walk every page and write a copy of its source markdown alongside the HTML
// output, with intra-docs links rewritten to point at other mirrors. The
// command reference is emitted unchanged (its <section> wrapping is purely
// an HTML concern).
function emitMarkdownMirrors() {
  let count = 0;
  for (const page of allPages) {
    const src = readFile(page.sourcePath);
    const { meta, body } = parseFrontmatter(src);
    const processedBody = preprocessExample(body, meta, page);
    // Re-emit the original frontmatter block verbatim (preserving its
    // formatting), then the resolved body.
    const fmMatch = src.match(/^---\n[\s\S]*?\n---\n?/);
    const frontmatter = fmMatch ? fmMatch[0] : '';
    const rewritten = frontmatter + rewriteLinksToMd(processedBody);
    const outPath = path.join(OUT_DIR, page.outRel + '.md');
    ensureDir(path.dirname(outPath));
    fs.writeFileSync(outPath, rewritten);
    count++;
  }
  return count;
}

// Write llms.txt at the *site* root (www/llms.txt), following the
// convention at https://llmstxt.org/ that agents check the apex domain.
// Section overview pages and the top-level Home / What's new pages are
// grouped under "Optional" so a context-constrained agent can drop them
// first.
function emitLlmsTxt() {
  const intro = fs.existsSync(LLMS_INTRO_PATH)
    ? readFile(LLMS_INTRO_PATH).trim()
    : '# Mapshaper\n\n> Geographic data editor.';
  const lines = [intro, ''];

  // A section page is treated as an overview (and goes under "Optional") only
  // when it's labelled "Overview" and the section has other pages. Any other
  // label means the page is substantive content and belongs in the main
  // listing under its own name.
  function isOverviewEntry(navEntry, section) {
    if (!navEntry.file) return false;
    if ((navEntry.label || '').trim().toLowerCase() !== 'overview') return false;
    const others = section.pages.filter(p => p.file && p !== navEntry);
    return others.length > 0;
  }

  for (const section of nav.sections || []) {
    const entries = [];
    for (const navEntry of section.pages) {
      if (!navEntry.file) continue;
      if (isOverviewEntry(navEntry, section)) continue;
      const page = allPages.find(p =>
        p.kind === 'section' && p.sectionPath === section.path && p.file === navEntry.file);
      if (!page) continue;
      const desc = pageDescription(page, navEntry);
      const tail = desc ? `: ${desc}` : '';
      entries.push(`- [${navEntry.label}](${mdMirrorUrl(page)})${tail}`);
    }
    if (!entries.length) continue;
    lines.push(`## ${section.label}`);
    lines.push('');
    lines.push(...entries);
    lines.push('');
  }

  // Top-link file entries marked mainContent:true appear in the main listing.
  for (const link of nav.topLinks || []) {
    if (!link.file || !link.mainContent) continue;
    const page = allPages.find(p => p.kind === 'top' && p.file === link.file);
    if (!page) continue;
    const desc = pageDescription(page, link);
    const tail = desc ? `: ${desc}` : '';
    lines.push(`## ${link.label}`);
    lines.push('');
    lines.push(`- [${link.label}](${mdMirrorUrl(page)})${tail}`);
    lines.push('');
  }

  const optional = [];
  for (const link of nav.topLinks || []) {
    if (!link.file || link.mainContent) continue;
    const page = allPages.find(p => p.kind === 'top' && p.file === link.file);
    if (!page) continue;
    const desc = pageDescription(page, link);
    const tail = desc ? `: ${desc}` : '';
    optional.push(`- [${link.label}](${mdMirrorUrl(page)})${tail}`);
  }
  for (const section of nav.sections || []) {
    const navEntry = section.pages.find(p => isOverviewEntry(p, section));
    if (!navEntry) continue;
    const page = allPages.find(p =>
      p.kind === 'section' && p.sectionPath === section.path && p.file === navEntry.file);
    if (!page) continue;
    const desc = pageDescription(page, navEntry);
    const tail = desc ? `: ${desc}` : '';
    optional.push(`- [${section.label} overview](${mdMirrorUrl(page)})${tail}`);
  }
  if (optional.length) {
    lines.push('## Optional');
    lines.push('');
    lines.push(...optional);
    lines.push('');
  }

  fs.writeFileSync(path.join(WWW_DIR, 'llms.txt'), lines.join('\n'));
}

// Write llms-full.txt at the site root: the intro followed by every page's
// markdown body
// (frontmatter stripped, links rewritten to the .md mirrors), separated by
// horizontal rules. This is the single-file fallback for agents that can
// swallow the whole corpus in one bite.
function emitLlmsFullTxt() {
  const lines = [];
  if (fs.existsSync(LLMS_INTRO_PATH)) {
    lines.push(readFile(LLMS_INTRO_PATH).trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }
  for (const page of allPages) {
    const { body } = parseFrontmatter(readFile(page.sourcePath));
    lines.push(`<!-- ${SITE_URL}${page.url} -->`);
    lines.push('');
    lines.push(rewriteLinksToMd(body).trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }
  fs.writeFileSync(path.join(WWW_DIR, 'llms-full.txt'), lines.join('\n'));
}

// --- build ------------------------------------------------------------

// Copy a highlight.js theme stylesheet into the docs assets dir, so it can
// be served from /docs/_assets/highlight.css alongside our own stylesheet.
function copyHighlightTheme(destDir) {
  const src = path.join(HERE, 'node_modules', 'highlight.js', 'styles', 'github-dark.min.css');
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(destDir, 'highlight.css'));
  } else {
    console.warn('highlight.js theme not found; skipping');
  }
}

function build() {
  // Wipe and recreate output dir, but only the docs subtree.
  if (fs.existsSync(OUT_DIR)) {
    fs.rmSync(OUT_DIR, { recursive: true, force: true });
  }
  ensureDir(OUT_DIR);
  copyDir(ASSETS_DIR, path.join(OUT_DIR, '_assets'));
  copyHighlightTheme(path.join(OUT_DIR, '_assets'));
  // Copy a shared image directory for content images referenced from any
  // docs page as /docs/images/<file>.
  const imagesSrc = path.join(SRC_DIR, 'images');
  if (fs.existsSync(imagesSrc)) {
    copyDir(imagesSrc, path.join(OUT_DIR, 'images'));
  }
  // Copy any per-section data directory verbatim so example pages can
  // reference images, snapshots and download bundles via stable URLs like
  // /docs/examples/data/<file>.
  copyDir(path.join(SRC_DIR, 'examples', 'data'),
          path.join(OUT_DIR, 'examples', 'data'));

  let count = 0;
  for (const page of allPages) {
    const outPath = path.join(OUT_DIR, page.outRel);
    ensureDir(path.dirname(outPath));
    fs.writeFileSync(outPath, renderPage(page));
    count++;
  }
  const mirrorCount = emitMarkdownMirrors();
  emitLlmsTxt();
  emitLlmsFullTxt();
  console.log(
    `Built ${count} docs pages and ${mirrorCount} markdown mirrors -> ` +
    `${path.relative(HERE, OUT_DIR)}/, ` +
    `plus llms.txt and llms-full.txt -> ${path.relative(HERE, WWW_DIR)}/`
  );
}

build();
